//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    using Web.Helper;

    public partial class UserLogin
    {
        public string ID { get; set; }
        public string CompanyID { get; set; }
        public string UserName { get; set; }
        public string ScreenName { get; set; }
        public string AccessLevel { get; set; }

        public bool IsSystemAdministrator
        {
            get
            {
                return "38f65c64-37b0-4a6a-b945-1f879a1e1c13".Equals(ID, StringComparison.OrdinalIgnoreCase);
            }
        }

        public Common.ApplicationRole Role
        {
            get
            {
                if(AccessLevel.ToLower().Contains("*") || AccessLevel.ToLower().Contains("systemadministrator"))
                {
                    return Common.ApplicationRole.SystemAdministrator;
                }

                if (AccessLevel.ToLower().Contains("administrator"))
                {
                    return Common.ApplicationRole.Administrator;
                }

                if (AccessLevel.ToLower().Contains("companyadmin"))
                {
                    return Common.ApplicationRole.CompanyAdmin;
                }

                if (AccessLevel.ToLower().Contains("student"))
                {
                    return Common.ApplicationRole.Student;
                }

                return Common.ApplicationRole.Guest;
            }
        }
    }
}
